# Generated by Django 2.1.1 on 2018-09-11 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_tittle', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField()),
                ('post_content', models.CharField(max_length=500)),
                ('post_key', models.CharField(max_length=200)),
            ],
        ),
    ]
